baseURL = "//www.wrongdirection.info.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-gb"
title = "Team Wrong Direction"
theme = "hyde-y"

# Copyright
copyright = "(c) 2015 Team Wrong Direction."

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "yaml"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
# disqusShortname = "your_disqus_shortname"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Wrong Direction"
    # email = "yourname@example.com"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "About"
    topline = "Follow Team Wrong Direction as we head to Morocco to take part in Horizons Unlimited Mountain Madness and discover the sun, sand and beer (especially the beer) of North Africa."
    footline = "code with <i class='fa fa-heart'></i>"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "right"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Google Analytics.
    # googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
    # googleplus = "115763365761941520169"
    twitter = "wrongdirect2015"
    youtube = "UCwh4sGERdUcXfVFuxFXPl6A"

    # Sidebar RSS link: will only show up if there is a RSS feed
    # associated with the current page
    rss = false

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
